### ISSUE TITLE
instructions on how to change path with termial missing

### ISSUE THREAD

**Issue by ratnanil** [Modul-AGI/HS21#1]

**Comment by ratnanil** [comment]
@KimboGilda! Careful; we are already talking about this topic here: https://modul-agi.github.io/HS21/B_Coding_in_GIS_1/7_Tabellarische_Daten.html#ubung-4-2

Extend this with: save (save as...) your ipynb before closing jupyter

**Comment by KimboGilda** [comment]
@ratnanil I added the respective instructions, as minimum as possible. It's a little bit different from the one you are reffering to above. My perspective was to implement it in a way that the students will "copy" the steps as much as possible, so we can avoid potential caveats like `cd` etc. Check it here: https://modul-agi.github.io/HS21/B_Coding_in_GIS_1/2_Python-Command-Prompt.html
Tomorrow I will not be working in the morning, but after 17:30 I can again add smt that is missing

**Comment by KimboGilda** [comment]
@ratnanil after rethinking the whole thing, I do not believe it makes sense to tell them to change directory in the first exercises, where they use the command prompt as an environment to run some basic commands. It makes sense only after using `jupyter notebook`. So I will add some stuff in that chapter.

**Comment by ratnanil** [comment]
I will also close this after checking it tomorrow!
