### ISSUE TITLE
reveal solutions, build book and push

### ISSUE THREAD

**Issue by ratnanil** [Modul-AGI/HS21#6]
@KimboGilda : hey nikos! I have the solutions for all exercises ready and woul have liked to publish them aufgabe by aufgabe on wednesday. Question: can you take over this part? In order to be able to do this you must:

- have a conda environment with all required packages (see requirements.txt)
- understand and be able to execute the stript "show_hide_solutions.py"
- push changes form build/html to the `gh-pages` branch using the `ghp-import`-tool (`ghp-import -p -n build/html/`)

**Comment by ratnanil** [comment]
do you think you could have a look at this tommorow and tell me if this is possible for you?

**Comment by KimboGilda** [comment]
@ratnanil hey Nils. Today I am with Nefeli. I will try to have a look at it late in the afternoon.

**Comment by ratnanil** [comment]
oh completely forgot.. don't worry about it, we'll have a look at it tomorrow
