### ISSUE TITLE
absolute paths to datasets

### ISSUE THREAD

**Issue by ratnanil** [Modul-AGI/HS21#9]
downloadable datasets (e.g. [here](https://modul-agi.github.io/HS21/D_Netzwerkanalyse_3/7_Anhang.html#table-datensaetze-netzwerkanalyse))have hardcoded urls and still link to the repo of hs20. can we replace these with relative paths, @KimboGilda ?

**Comment by KimboGilda** [comment]
yes sure, I will do it. I will adjust it tomorrow with, as I will do for Netzwerk II.
